### ISSUE TITLE
WM: services map taxonomy

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#351]
The services map layer taxonomy is not being reflected on the map.
![screenshot 2016-05-12 10 12 19](https://cloud.githubusercontent.com/assets/6032426/15217650/84731e88-182a-11e6-987a-c270b76c6d19.png)

![screenshot 2016-05-12 10 13 13](https://cloud.githubusercontent.com/assets/6032426/15217636/7112dba8-182a-11e6-94ba-95fc38d97b78.png)

![screenshot 2016-05-12 10 13 41](https://cloud.githubusercontent.com/assets/6032426/15217635/71106512-182a-11e6-8b6b-2d167cb31541.png)

**Comment by jlyon** [comment]
OK, I got to the bottom of it. The order of the map is saved when you save the panel settings, so the taxonomy order doesn't actually affect a map until the map settings panel edit form is saved.

I think you went through these steps:
1. create all taxonomy terms
2. set up homepage map, check the taxonomy terms to be included
3. re-order taxonomy terms

If you add a 
4. edit homepage map and resave settings

The order is fixed.  I fixed this on the WM homepage.

**Comment by jlyon** [comment]
Hmm, actually it seems like this hasn't fixed it on the demo site. It worked for me when I tested it locally.  I'll need to do more testing on this one.

**Comment by jlyon** [comment]
This appears to be fixed, but perhaps the taxonomy terms need to be re-ordered on https://westmead.org/wp-admin/edit.php?post_type=proud_location&page=to-interface-proud_location @kevindherman ?

**Comment by kevindherman** [comment]
@jlyon I don't think it's fixed. I moved 'featured' to the top of the taxonomy list but it's still the bottom option on the businesses map: https://westmead.org/businesses/#/city/answers

**Comment by jlyon** [comment]
Fixed this on WM homepage by:

1. Editing the homepage
2. Editing map widget
3. Checking "Restaurants"
4. Saving
5. Edting map widget again
6. Unchecking "Restaurants"
7. Saving again

Basically they should try to add the Location layers and get them in the right order before editing map widget.

I created a new ticket #408 to update all map layers when the taxonomy order is updated, but it's probably more work than it's worth.
